from pyrogram import Client, filters
import asyncio 
import time

api_id = "16930763"
api_hash = "e0103a0abd81147727ecfad636af7fec"

app = Client("account", api_id, api_hash)

@app.on_message(filters.regex("Black"))
async def blackanim(client, message):
    await message.edit_text("**Анимация будет запущена через 3 секунды...**")
    await asyncio.sleep(3)
    await message.edit_text("🖤")
    await asyncio.sleep(0.001)
    await message.edit_text("🖤🖤")
    await asyncio.sleep(0.001)
    await message.edit_text("🖤🖤🖤")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤\n **TIME TO WHITE**")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤\n **TIME TO WHIT**")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤\n **TIME TO WHI**")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤\n **TIME TO WH**")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤\n **TIME TO W**")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤\n **TIME TO**")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤\n **TIME T**")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤\n **TIME**")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤\n **TIM**")   
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤\n **TI**")    
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤\n **T**")    
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤\n")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤\n🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤\n🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍\n🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤\n🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍\n🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤\n🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍\n🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤\n🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍\n🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤\n🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍\n🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤\n🤍🤍🤍🤍🤍🤍🤍")
    await asyncio.sleep(0.0001)
    await message.edit_text("🖤🖤🖤🖤🖤🖤🖤\n🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍\n🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤\n🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍🤍\n🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤🖤")


app.run()       
